server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iloveshopping_db
    username: postgres
    password: kvit@psql
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-expiration-ms: 900000
  refresh-expiration-ms: 604800000

google:
  recaptcha:
    secret: ${GOOGLE_RECAPTCHA_SECRET:6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe}
    url: https://www.google.com/recaptcha/api/siteverify
