import React, { FormEvent, useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Product = { id:string; name:string; description?:string; price:number; stockQuantity:number; imageUrl?:string };
type CartItem = { id:number; productId:string; productName:string; unitPrice:number; imageUrl?:string; quantity:number; subTotal:number };
type Cart = { id:number; items:CartItem[]; totalAmount:number };
type Order = { id:number; status:string; totalAmount:number; customerEmail:string; customerFirstName?:string; customerLastName?:string; customerPhone?:string; shippingAddress:string; shippingMethod:string; trackingNumber?:string; createdAt:string; items:CartItem[] };
type View = 'shop'|'cart'|'checkout'|'orders'|'account';
type Profile = { email:string; firstName:string; lastName:string };
const guestId = localStorage.getItem('guest-session-id') || crypto.randomUUID(); localStorage.setItem('guest-session-id', guestId);
const money = (v:number) => new Intl.NumberFormat('en-US', {style:'currency',currency:'USD'}).format(v);

function App() {
 const [view,setView]=useState<View>('shop'), [token,setToken]=useState(localStorage.getItem('access-token')||''), [cart,setCart]=useState<Cart>({id:0,items:[],totalAmount:0}), [products,setProducts]=useState<Product[]>([]), [query,setQuery]=useState(''), [notice,setNotice]=useState(''), [profile,setProfile]=useState<Profile>();
 const headers=useMemo(()=>({ 'Content-Type':'application/json', ...(token?{Authorization:`Bearer ${token}`}:{'X-Guest-Session-Id':guestId}) }),[token]);
 const api=async(path:string, options:RequestInit={})=>{ let r:Response; try{r=await fetch('/api/v1'+path,{...options,headers:{...headers,...options.headers}})}catch{throw new Error('Network error: cannot reach the shop. Check that Docker is running and try again.')} const body=await r.text(); const json=body && r.headers.get('content-type')?.includes('application/json'); if(!r.ok) throw new Error(json ? (JSON.parse(body).error||body) : (body||'Request failed')); return body ? (json ? JSON.parse(body) : body) : null; };
 const loadCart=async()=>{ try {setCart(await api('/cart'));}catch(e){setNotice((e as Error).message)} };
 const loadProducts=async()=>{ try {const p=await api(`/products/search?query=${encodeURIComponent(query)}&page=0&size=40`);setProducts(p.content||[])}catch(e){setNotice((e as Error).message)} };
 useEffect(()=>{loadCart();loadProducts(); if(token) api('/auth/me').then(setProfile).catch(()=>setProfile(undefined));},[token]);
 const add=async(id:string)=>{try{setCart(await api('/cart/items',{method:'POST',body:JSON.stringify({productId:id,quantity:1})}));setNotice('Added to cart')}catch(e){setNotice((e as Error).message)}};
 const update=async(id:number,quantity:number)=>{try{setCart(await api(`/cart/items/${id}`,{method:'PUT',body:JSON.stringify({quantity})}))}catch(e){setNotice((e as Error).message)}};
 const remove=async(id:number)=>{try{setCart(await api(`/cart/items/${id}`,{method:'DELETE'}))}catch(e){setNotice((e as Error).message)}};
 const signOut=()=>{localStorage.removeItem('access-token');setToken('');setView('shop');setNotice('Signed out')};
 return <main><header><button className="brand" onClick={()=>setView('shop')}>I Love Shopping</button><nav>{(['shop','cart','checkout','orders','account'] as View[]).map(x=><button key={x} onClick={()=>setView(x)}>{x==='cart'?`Cart (${cart.items.length})`:x}</button>)}{token&&<button onClick={signOut}>Sign out</button>}</nav></header>{notice&&<p className="notice">{notice}<button onClick={()=>setNotice('')}>×</button></p>}
 {view==='shop'&&<Shop products={products} query={query} setQuery={setQuery} search={loadProducts} add={add}/>} {view==='cart'&&<CartView cart={cart} products={products} update={update} remove={remove} add={add} checkout={()=>setView('checkout')}/>} {view==='checkout'&&<Checkout cart={cart} profile={profile} api={api} done={(o:Order)=>{setCart({id:0,items:[],totalAmount:0});setNotice(`Order #${o.id} created: ${o.status}`);setView('orders')}}/>} {view==='orders'&&<Orders api={api} signedIn={!!token} setNotice={setNotice}/>} {view==='account'&&<Account api={api} signedIn={!!token} loggedIn={(t:string)=>{localStorage.setItem('access-token',t);setToken(t);setNotice('Signed in; your cart is now persistent')}}/>}</main>
}
function Shop(p:{products:Product[];query:string;setQuery:(x:string)=>void;search:()=>void;add:(id:string)=>void}) { return <section><h1>Shop</h1><form className="search" onSubmit={e=>{e.preventDefault();p.search()}}><input value={p.query} onChange={e=>p.setQuery(e.target.value)} placeholder="Search products"/><button>Search</button></form><div className="grid">{p.products.map(x=><article className="product" key={x.id}>{x.imageUrl?<img src={x.imageUrl} alt=""/>:<div className="placeholder">No image</div>}<h2>{x.name}</h2><p>{x.description}</p><strong>{money(x.price)}</strong><small>{x.stockQuantity} in stock</small><button disabled={!x.stockQuantity} onClick={()=>p.add(x.id)}>Add to cart</button></article>)}</div>{!p.products.length&&<p>No products found. Add catalog products through the existing catalog data source.</p>}</section> }
function CartView(p:{cart:Cart;products:Product[];update:(id:number,q:number)=>void;remove:(id:number)=>void;add:(id:string)=>void;checkout:()=>void}) {const inCart=new Set(p.cart.items.map(i=>i.productId));const suggestions=p.products.filter(x=>!inCart.has(x.id)&&x.stockQuantity>0).slice(0,3);return <section><h1>Your cart</h1>{!p.cart.items.length?<p>Your cart is empty.</p>:<><table><thead><tr><th>Item</th><th>Price</th><th>Quantity</th><th>Total</th><th/></tr></thead><tbody>{p.cart.items.map(i=><tr key={i.id}><td>{i.imageUrl&&<img className="thumb" src={i.imageUrl}/>} {i.productName}</td><td>{money(i.unitPrice)}</td><td><input aria-label={`Quantity for ${i.productName}`} type="number" min="1" value={i.quantity} onChange={e=>p.update(i.id,+e.target.value)}/></td><td>{money(i.subTotal)}</td><td><button onClick={()=>p.remove(i.id)}>Remove</button></td></tr>)}</tbody></table><h2 className="total">Total: {money(p.cart.totalAmount)}</h2><button onClick={p.checkout}>Checkout</button>{suggestions.length>0&&<><h2>You may also like</h2><div className="suggestions">{suggestions.map(x=><article key={x.id}><strong>{x.name}</strong><span>{money(x.price)}</span><button onClick={()=>p.add(x.id)}>Add</button></article>)}</div></>}</>}</section>}
function Checkout(p:{cart:Cart;profile?:Profile;api:(x:string,o?:RequestInit)=>Promise<any>;done:(x:Order)=>void}) {
 const [form,setForm]=useState({email:p.profile?.email||'',firstName:p.profile?.firstName||'',lastName:p.profile?.lastName||'',address:'',city:'',zipCode:'',phone:'',shippingOptionId:'standard',paymentMethodToken:'tok_sandbox_success'}), [card,setCard]=useState({number:'4242 4242 4242 4242',expiry:'12/30',cvc:'123'}), [busy,setBusy]=useState(false), [error,setError]=useState('');
 useEffect(()=>{if(p.profile)setForm(f=>({...f,...p.profile}))},[p.profile]);
 const validCard=()=>{const digits=card.number.replace(/\D/g,'');const luhn=digits.split('').reverse().reduce((sum,digit,i)=>{let n=+digit;if(i%2)n=n>4?n*2-9:n*2;return sum+n},0)%10===0;const [month,year]=card.expiry.split('/').map(Number);return digits.length>=13&&digits.length<=19&&luhn&&month>=1&&month<=12&&year>=new Date().getFullYear()%100&&/^\d{3,4}$/.test(card.cvc)};
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');if(!validCard()){setError('Payment validation failed: enter a valid card number, future expiry date, and 3–4 digit CVC.');return;}setBusy(true);try{p.done(await p.api('/orders/checkout',{method:'POST',body:JSON.stringify(form)}))}catch(x){setError((x as Error).message)}finally{setBusy(false)}};
 return <section><h1>Checkout</h1>{!p.cart.items.length?<p>Your cart is empty.</p>:<form className="checkout" onSubmit={submit}><div><h2>Contact & shipping</h2>{Object.entries(form).slice(0,7).map(([k,v])=><label key={k}>{k.replace(/([A-Z])/g,' $1')}<input required type={k==='email'?'email':k==='phone'?'tel':'text'} value={v} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Shipping method</label><select value={form.shippingOptionId} onChange={e=>setForm({...form,shippingOptionId:e.target.value})}><option value="standard">Standard — included</option><option value="express">Express — included in sandbox</option></select></div><div><h2>Secure payment</h2><p>Sandbox hosted fields: these values are validated in the browser and tokenized; card data is never submitted to this API.</p><label>Card number<input inputMode="numeric" autoComplete="cc-number" value={card.number} onChange={e=>setCard({...card,number:e.target.value})}/></label><label>Expiry (MM/YY)<input inputMode="numeric" autoComplete="cc-exp" value={card.expiry} onChange={e=>setCard({...card,expiry:e.target.value})}/></label><label>CVC<input inputMode="numeric" autoComplete="cc-csc" value={card.cvc} onChange={e=>setCard({...card,cvc:e.target.value})}/></label><label>Sandbox payment result<select value={form.paymentMethodToken} onChange={e=>setForm({...form,paymentMethodToken:e.target.value})}><option value="tok_sandbox_success">Successful payment</option><option value="tok_insufficient_funds">Insufficient funds</option><option value="tok_invalid_card">Invalid card</option><option value="tok_expired_card">Expired card</option><option value="tok_gateway_timeout">Gateway timeout</option></select></label><h2>Order summary</h2>{p.cart.items.map(i=><p key={i.id}>{i.productName} × {i.quantity}: {money(i.subTotal)}</p>)}<p>Shipping: included</p><h2>Order total: {money(p.cart.totalAmount)}</h2>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Placing order…':'Place order'}</button></div></form>}</section>}
function Orders(p:{api:(x:string,o?:RequestInit)=>Promise<any>;signedIn:boolean;setNotice:(x:string)=>void}) {const [orders,setOrders]=useState<Order[]>([]),[status,setStatus]=useState(''),[startDate,setStartDate]=useState(''),[endDate,setEndDate]=useState(''); const load=async()=>{try{const q=new URLSearchParams();if(status)q.set('status',status);if(startDate)q.set('startDate',startDate);if(endDate)q.set('endDate',endDate);setOrders(await p.api(`/orders${q.size?`?${q}`:''}`))}catch(e){p.setNotice((e as Error).message)}}; useEffect(()=>{if(p.signedIn)load()},[p.signedIn]); if(!p.signedIn)return <section><h1>Orders</h1><p>Sign in to view and manage your orders.</p></section>; return <section><h1>Orders</h1><div className="filters"><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option><option>PENDING_PAYMENT</option><option>PAYMENT_SUCCESSFUL</option><option>PAYMENT_FAILED</option><option>CANCELLED</option></select></label><label>From<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>To<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><button onClick={load}>Apply filters</button></div>{orders.map(o=><article className="order" key={o.id}><h2>Order #{o.id} — {o.status}</h2><p>{new Date(o.createdAt).toLocaleString()} · {money(o.totalAmount)} · {o.shippingMethod}</p><details><summary>View order details</summary><p>Customer: {[o.customerFirstName,o.customerLastName].filter(Boolean).join(' ')||'Not retained on legacy order'}</p><p>Email: {o.customerEmail}</p><p>Phone: {o.customerPhone||'Not retained on legacy order'}</p><p>Delivery address: {o.shippingAddress}</p><p>Tracking: {o.trackingNumber||'Assigned after successful payment'}</p><ul>{o.items.map(i=><li key={i.id}>{i.productName} × {i.quantity} — {money(i.subTotal)}</li>)}</ul></details>{!['CANCELLED','SHIPPED','DELIVERED'].includes(o.status)&&<button onClick={async()=>{try{await p.api(`/orders/${o.id}/cancel`,{method:'POST'});p.setNotice('Order cancelled');load()}catch(e){p.setNotice((e as Error).message)}}}>Cancel / request refund</button>}</article>)}{!orders.length&&<p>No orders match these filters.</p>}</section>}
function Account(p:{api:(x:string,o?:RequestInit)=>Promise<any>;signedIn:boolean;loggedIn:(x:string)=>void}) {const [register,setRegister]=useState(false),[form,setForm]=useState({email:'',password:'',firstName:'',lastName:''}),[message,setMessage]=useState(''); const submit=async(e:FormEvent)=>{e.preventDefault();try{if(register){await p.api('/auth/register',{method:'POST',body:JSON.stringify({...form,recaptchaToken:'dummy-captcha'})});setMessage('Registered. You can now sign in.')}else{const r=await p.api('/auth/login',{method:'POST',body:JSON.stringify({email:form.email,password:form.password})});if(r.requires2FA)throw new Error('Two-factor verification is required');await fetch('/api/v1/cart/merge',{method:'POST',headers:{Authorization:`Bearer ${r.accessToken}`,'X-Guest-Session-Id':guestId}});p.loggedIn(r.accessToken)}}catch(x){setMessage((x as Error).message)}};if(p.signedIn)return <section><h1>Account</h1><p>You are signed in. Your cart persists between sessions, and checkout can use your account.</p></section>;return <section><h1>{register?'Create account':'Sign in'}</h1><form className="account" onSubmit={submit}><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{register&&<><label>First name<input required value={form.firstName} onChange={e=>setForm({...form,firstName:e.target.value})}/></label><label>Last name<input required value={form.lastName} onChange={e=>setForm({...form,lastName:e.target.value})}/></label></>}<button>{register?'Register':'Sign in'}</button></form>{message&&<p className="error">{message}</p>}<button className="link" onClick={()=>setRegister(!register)}>{register?'Already registered? Sign in':'Need an account? Register'}</button></section>}
createRoot(document.getElementById('root')!).render(<App/>);
